/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.gym.pruebas;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import pe.gym.combos.JComboBoxEjercicio;
import pe.gym.model.Cargo;
import pe.gym.model.Ejercicio;
import pe.gym.model.TipoEjercicio;

/**
 *
 * @author Carlos
 */
public class PruebaCombos1 extends javax.swing.JFrame {

    /**
     * Creates new form PruebaCombos
     */
    private List<Cargo> lista = new ArrayList<>();

    public PruebaCombos1() {
        initComponents();
        jComboBoxEjercicio1.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldisplay = new javax.swing.JLabel();
        lblvalue = new javax.swing.JLabel();
        jComboBoxCargo1 = new pe.gym.combos.JComboBoxCargo();
        jButton1 = new javax.swing.JButton();
        jComboBoxTipoEjercicio1 = new pe.gym.combos.JComboBoxTipoEjercicio();
        jComboBoxEjercicio1 = new pe.gym.combos.JComboBoxEjercicio();
        btntipo = new javax.swing.JButton();
        btnejercicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbldisplay.setText("jLabel1");

        lblvalue.setText("jLabel1");

        jComboBoxCargo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCargo1ItemStateChanged(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxTipoEjercicio1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoEjercicio1ItemStateChanged(evt);
            }
        });

        btntipo.setText("Tipo");
        btntipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntipoActionPerformed(evt);
            }
        });

        btnejercicio.setText("Ejercicio");
        btnejercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejercicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblvalue)
                            .addComponent(lbldisplay)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jComboBoxCargo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxEjercicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnejercicio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxTipoEjercicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btntipo)))))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 224, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCargo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipoEjercicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEjercicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnejercicio))
                .addGap(20, 20, 20)
                .addComponent(lbldisplay)
                .addGap(28, 28, 28)
                .addComponent(lblvalue)
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCargo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCargo1ItemStateChanged

    }//GEN-LAST:event_jComboBoxCargo1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cargo cargo = (Cargo) jComboBoxCargo1.getSelectedItem();
        JOptionPane.showMessageDialog(null, "Codigo: " + cargo.getIdCargo());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btntipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntipoActionPerformed
        if (jComboBoxTipoEjercicio1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, jComboBoxTipoEjercicio1.getSelectedIndex());
            return;
        }
        TipoEjercicio tipo = (TipoEjercicio) jComboBoxTipoEjercicio1.getSelectedItem();
        JOptionPane.showMessageDialog(null, "Coddigo: " + tipo.getIdTipo());

    }//GEN-LAST:event_btntipoActionPerformed

    private void btnejercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejercicioActionPerformed
        if (jComboBoxEjercicio1.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null, jComboBoxEjercicio1.getSelectedIndex());
            return;
        }
        Ejercicio ejer = (Ejercicio) jComboBoxEjercicio1.getSelectedItem();
        JOptionPane.showMessageDialog(null, "Codigo: " + ejer.getIdTipo());
    }//GEN-LAST:event_btnejercicioActionPerformed

    private void jComboBoxTipoEjercicio1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoEjercicio1ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jComboBoxTipoEjercicio1.getSelectedIndex()==0) {
                jComboBoxEjercicio1.setSelectedIndex(0);
                jComboBoxEjercicio1.setEnabled(false);
            return;
            
        }
        
        TipoEjercicio tipo= (TipoEjercicio) jComboBoxTipoEjercicio1.getSelectedItem();
        String tip=tipo.getIdTipo();

        jComboBoxEjercicio1.setEnabled(true);
        jComboBoxEjercicio1.rellenaxcombo(tip);
        }
        
        
        
    }//GEN-LAST:event_jComboBoxTipoEjercicio1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaCombos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaCombos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaCombos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaCombos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaCombos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnejercicio;
    private javax.swing.JButton btntipo;
    private javax.swing.JButton jButton1;
    private pe.gym.combos.JComboBoxCargo jComboBoxCargo1;
    private pe.gym.combos.JComboBoxEjercicio jComboBoxEjercicio1;
    private pe.gym.combos.JComboBoxTipoEjercicio jComboBoxTipoEjercicio1;
    private javax.swing.JLabel lbldisplay;
    private javax.swing.JLabel lblvalue;
    // End of variables declaration//GEN-END:variables

}
