/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.gym.form;

import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pe.gym.controller.DetPagosController;
import pe.gym.controller.MembreController;
import pe.gym.controller.PagosController;
import pe.gym.controller.PlanesController;
import pe.gym.controller.PromocionesController;
import pe.gym.model.DetPagos;

import pe.gym.model.Membresia;
import pe.gym.model.Pagos;
import pe.gym.model.Planes;
import pe.gym.model.Promociones;
import pe.gym.util.CargaComponentes;


import static pe.gym.util.Herramientas.ObtenerFecha;
import static pe.gym.util.Herramientas.FechaActual;
import static pe.gym.util.Herramientas.fechasdepago;

/**
 *
 * @author Carlos
 */
public class GenerarPago extends javax.swing.JDialog {

    /**
     * Creates new form RegistraSocio
     */
    public static String idplan;
    public static String idpromo;
    public static String idmem;
    List listafechas = new ArrayList();

    Planes plan = new Planes();
    Promociones promo = new Promociones();
    Pagos pago= new Pagos();
    DetPagos detpagos= new DetPagos();
    

    public GenerarPago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        CargaComponentes carga = new CargaComponentes();
        carga.cargaIdEmpleado(jlblnomemp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jlblnomemp = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jtxtidsocio = new javax.swing.JLabel();
        jLabel1 = new org.edisoncor.gui.label.LabelHeader();
        jLabel5 = new javax.swing.JLabel();
        cbotipopago = new javax.swing.JComboBox<>();
        cbonumcuotas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("IdEmpleado: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nro de Cuotas:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Tipo de Pago:");

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(102, 0, 0));
        btnRegistrar.setText("GENERAR PAGO");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(102, 0, 0));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jtxtidsocio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jtxtidsocio.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("GENERAR PAGO");
        jLabel1.setColorDeSombra(new java.awt.Color(0, 112, 192));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("IdSocio: ");

        cbotipopago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbotipopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Contado", "Credito" }));

        cbonumcuotas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbonumcuotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1", "2", "3", "4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jlblnomemp, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtidsocio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbotipopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbonumcuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(216, 216, 216))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4))
                    .addComponent(jlblnomemp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtidsocio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(cbotipopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbonumcuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        PromocionesController controlpromo = new PromocionesController();
        PlanesController controlplan = new PlanesController();
        PagosController controlpago = new PagosController();
        DetPagosController controldetpagos= new DetPagosController();
        MembreController controlmembresia = new MembreController();
        try {
            plan = controlplan.leerxid(idplan);
            promo = controlpromo.leerxid(idpromo);
            if (cbotipopago.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de pago");
                return;
            }
            if (cbonumcuotas.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un número de cuota");
                return;
            }
            pago.setIdSocio(jtxtidsocio.getText());
            String tipopago = cbotipopago.getSelectedItem().toString();
            pago.setTipo_de_Pago(tipopago);
            int nrocuotas = Integer.parseInt(cbonumcuotas.getSelectedItem().toString());
            pago.setNroCuotas(nrocuotas);
            double total=plan.getImporte()-(plan.getImporte()*promo.getDescuento());
            double subtotal=total/1.18;
            double igv=total-subtotal;
            
            pago.setTotal(total);
            pago.setSubtotal(subtotal);
            pago.setIGV(igv);
            pago.setEstado("Pendiente");
            String fecha=ObtenerFecha(FechaActual());
            listafechas=fechasdepago(fecha, nrocuotas);
            try {
                controlpago.crear(pago);
                
                for (int i = 0; i < listafechas.size(); i++) {
                detpagos.setIdPago(pago.getIdPago());
                detpagos.setIdEmpleado(jlblnomemp.getText());
                detpagos.setNroCuota(i+1);
                detpagos.setImporte(total/nrocuotas);
                detpagos.setF_UPago(listafechas.get(i).toString());
                detpagos.setEstado("Pendiente");
                controldetpagos.crear(detpagos);
                
                controlmembresia.insertaPago(idmem, pago.getIdPago());
            }
                
            } catch (Exception e) {
                throw new Exception("Error."+e.getMessage());
            }

            JOptionPane.showMessageDialog(null, "Pago  generado Correctamente, su id es: "
                    + pago.getIdPago());


        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error. " + e.getMessage());
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GenerarPago dialog = new GenerarPago(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbonumcuotas;
    private javax.swing.JComboBox<String> cbotipopago;
    private org.edisoncor.gui.label.LabelHeader jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlblnomemp;
    private javax.swing.JLabel jtxtidsocio;
    // End of variables declaration//GEN-END:variables

    public void setRowData(String id) {

        Membresia membresia = new Membresia();
        MembreController controlm = new MembreController();
        membresia = controlm.leerxid(id);
        idmem=membresia.getIdMembresia();
        jtxtidsocio.setText(membresia.getIdSocio());
        idplan = membresia.getIdPlan();
        idpromo = membresia.getIdPromociones();
        PromocionesController control = new PromocionesController();
        promo = control.leerxid(idpromo);
        if (!"P0001".equals(promo.getIdPromociones())) {
            cbonumcuotas.setSelectedIndex(1);
            cbonumcuotas.setEnabled(false);
        }

    }

}
