/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.gym.form;

import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.util.Calendar;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pe.gym.controller.MembreController;
import pe.gym.controller.PlanesController;
import pe.gym.controller.PromocionesController;

import pe.gym.model.Membresia;
import pe.gym.model.Planes;
import pe.gym.model.Promociones;
import pe.gym.util.CargaComponentes;

import static pe.gym.util.Herramientas.IngresarFechaModificada;
import static pe.gym.util.Herramientas.ObtenerFecha;
import static pe.gym.util.Herramientas.IngresarFecha;
import static pe.gym.util.Herramientas.FechaActual;


/**
 *
 * @author Carlos
 */
public class RegistrarMembresias extends javax.swing.JDialog {

    /**
     * Creates new form RegistraSocio
     */
    Membresia mem = new Membresia();
    
    public static int resta=0;

    public RegistrarMembresias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jtxtidmem.setVisible(false);
        btnModificar.setVisible(false);
        jLabel14.setVisible(false);
        cbocongelado.setVisible(false);
        txtidsociomodal.setEditable(false);

        this.setLocationRelativeTo(null);
        CargaComponentes carga = new CargaComponentes();
        carga.cargaIdEmpleado(jlblnomemp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtidsociomodal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dateffin = new datechooser.beans.DateChooserCombo();
        cboestado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jlblnomemp = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jtxtidmem = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new org.edisoncor.gui.label.LabelHeader();
        jLabel13 = new javax.swing.JLabel();
        datefini = new datechooser.beans.DateChooserCombo();
        jComboBoxPlanes1 = new pe.gym.combos.JComboBoxPlanes();
        jComboBoxPromociones1 = new pe.gym.combos.JComboBoxPromociones();
        jLabel14 = new javax.swing.JLabel();
        cbocongelado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("IdEmpleado: ");

        txtidsociomodal.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txtidsociomodal.setForeground(new java.awt.Color(153, 153, 153));
        txtidsociomodal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtidsociomodalMouseClicked(evt);
            }
        });
        txtidsociomodal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidsociomodalActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Estado : ");

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Fecha Fin : ");

        dateffin.setCalendarBackground(new java.awt.Color(255, 255, 255));
        dateffin.setCalendarPreferredSize(new java.awt.Dimension(320, 200));
        dateffin.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
        dateffin.setFieldFont(new java.awt.Font("Segoe UI Black", java.awt.Font.PLAIN, 16));

        cboestado.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        cboestado.setForeground(new java.awt.Color(153, 153, 153));
        cboestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Anulado" }));
        cboestado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboestadoItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Promocion:");

        btnLimpiar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(102, 0, 0));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Plan:");

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(102, 0, 0));
        btnRegistrar.setText("REGISTRAR MEMBRESIA");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Socio:");

        btnSalir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(102, 0, 0));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jtxtidmem.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jtxtidmem.setForeground(new java.awt.Color(153, 153, 153));

        btnModificar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(102, 0, 0));
        btnModificar.setText("MODIFICAR MEMBRESIA");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel1.setText("REGISTRAR MEMBRESIA");
        jLabel1.setColorDeSombra(new java.awt.Color(0, 112, 192));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Fecha Inicio:");

        datefini.setCalendarBackground(new java.awt.Color(255, 255, 255));
        datefini.setCalendarPreferredSize(new java.awt.Dimension(320, 200));
        datefini.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
        datefini.setFieldFont(new java.awt.Font("Segoe UI Black", java.awt.Font.PLAIN, 16));
        datefini.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                datefiniOnSelectionChange(evt);
            }
        });

        jComboBoxPlanes1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxPlanes1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPlanes1ItemStateChanged(evt);
            }
        });

        jComboBoxPromociones1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Nro Semanas Congelado: ");

        cbocongelado.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        cbocongelado.setForeground(new java.awt.Color(153, 153, 153));
        cbocongelado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4" }));
        cbocongelado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbocongeladoItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("IdMembresia: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateffin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(datefini, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbocongelado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jlblnomemp, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxPlanes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxPromociones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(txtidsociomodal, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtidmem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4))
                    .addComponent(jlblnomemp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtidmem, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidsociomodal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jComboBoxPlanes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxPromociones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datefini, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateffin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbocongelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtidsociomodal.setText("");

        datefini.setSelectedDate(FechaActual());
        dateffin.setSelectedDate(FechaActual());
        cboestado.setSelectedIndex(-1);


    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        try {
            if (jComboBoxPlanes1.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Seleccione un plan");
                return;
            }
            if (jComboBoxPromociones1.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Seleccione una promocion");
                return;
            }
            Planes plan = (Planes) jComboBoxPlanes1.getSelectedItem();
            Promociones promo = (Promociones) jComboBoxPromociones1.getSelectedItem();
            MembreController control = new MembreController();
            Membresia bean = new Membresia();
            bean.setIdEmpleado(jlblnomemp.getText());
            bean.setIdSocio(txtidsociomodal.getText());
            bean.setIdPlan(plan.getIdPlan());
            bean.setIdPromociones(promo.getIdPromociones());
            bean.setIdPago(null);
            String fechaini = ObtenerFecha(datefini.getSelectedDate());
            bean.setF_Inicio(fechaini);
            String fechafin = ObtenerFecha(dateffin.getSelectedDate());
            bean.setF_Fin(fechafin);

            bean.setEstado(cboestado.getSelectedItem().toString());

            control.RegistrarMembresia(bean);

            JOptionPane.showMessageDialog(null, "Membresia  creado Correctamente, su id es: "
                    + bean.getIdMembresia());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error. " + e.getMessage());
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        try {
            String idmem=jtxtidmem.getText();
            
            MembreController control = new MembreController();

            Membresia bean = new Membresia();
            bean.setIdMembresia(idmem);
            String fechaini = ObtenerFecha(datefini.getSelectedDate());
            bean.setF_Inicio(fechaini);
            String fechafin = ObtenerFecha(dateffin.getSelectedDate());
            bean.setF_Fin(fechafin);
            bean.setEstado(cboestado.getSelectedItem().toString());
            

            if (cboestado.getSelectedItem() == "Congelado") {
                try {
                    if (cbocongelado.getSelectedIndex() == 0) {
                        JOptionPane.showMessageDialog(null, "Seleccione un numero");
                        return;
                    }
                    int num = Integer.parseInt(cbocongelado.getSelectedItem().toString());
                    control.creaCongelamiento(idmem, ObtenerFecha(IngresarFechaModificada(dateffin.getSelectedDate(), 0, -num)), "Congelado");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error. " + e.getMessage());
                    return;
                }

            }

            control.ModificaMembresia(bean);

            JOptionPane.showMessageDialog(null, "Membresia modificada Correctamente, su id es: "
                    + bean.getIdMembresia());

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error. " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jComboBoxPlanes1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPlanes1ItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            try {
                dateffin.setSelectedDate(datefini.getSelectedDate());
                System.out.println(ObtenerFecha(datefini.getSelectedDate()));
                int aumento = 0;
                int aumento2 = 0;
                if (jComboBoxPlanes1.getSelectedIndex() == 0) {
                    return;
                }
                Planes plan = (Planes) jComboBoxPlanes1.getSelectedItem();
                aumento = plan.getNroMeses();
                aumento2 = 0;
                dateffin.setSelectedDate(IngresarFechaModificada(dateffin.getSelectedDate(), aumento, aumento2));

            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jComboBoxPlanes1ItemStateChanged

    private void txtidsociomodalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidsociomodalActionPerformed

    }//GEN-LAST:event_txtidsociomodalActionPerformed

    private void txtidsociomodalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidsociomodalMouseClicked
        BuscarSocioModal view;
        view = new BuscarSocioModal(new JFrame(), true);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
        
        mem.getIdSocio();
    }//GEN-LAST:event_txtidsociomodalMouseClicked

    private void cboestadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboestadoItemStateChanged
        if (cboestado.getSelectedItem() == "Congelado") {
            jLabel14.setVisible(true);
            cbocongelado.setVisible(true);
        } else {

            jLabel14.setVisible(false);
            cbocongelado.setVisible(false);
        }
    }//GEN-LAST:event_cboestadoItemStateChanged

    private void cbocongeladoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbocongeladoItemStateChanged


        if (evt.getStateChange() == ItemEvent.SELECTED) {

//            Planes plan = (Planes) jComboBoxPlanes1.getSelectedItem();
//            dateffin.setSelectedDate(datefini.getSelectedDate());
            dateffin.setSelectedDate(IngresarFechaModificada(dateffin.getSelectedDate(), 0, -resta));
            if (cbocongelado.getSelectedIndex() == 0) {
                resta=0;
                return;
            }
            
            
            String num = cbocongelado.getSelectedItem().toString();
            int numero = Integer.parseInt(num);
            resta=numero;
            dateffin.setSelectedDate(IngresarFechaModificada(dateffin.getSelectedDate(), 0, numero));
            
        }


    }//GEN-LAST:event_cbocongeladoItemStateChanged

    private void datefiniOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_datefiniOnSelectionChange

        try {
            if ("REGISTRAR MEMBRESIA".equals(jLabel1.getText())) {
                Calendar cal = datefini.getSelectedDate();
                dateffin.setSelectedDate(cal);
                jComboBoxPlanes1.setSelectedIndex(0);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_datefiniOnSelectionChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarMembresias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarMembresias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarMembresias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarMembresias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrarMembresias dialog = new RegistrarMembresias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbocongelado;
    private javax.swing.JComboBox<String> cboestado;
    private datechooser.beans.DateChooserCombo dateffin;
    private datechooser.beans.DateChooserCombo datefini;
    private pe.gym.combos.JComboBoxPlanes jComboBoxPlanes1;
    private pe.gym.combos.JComboBoxPromociones jComboBoxPromociones1;
    private org.edisoncor.gui.label.LabelHeader jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlblnomemp;
    private javax.swing.JLabel jtxtidmem;
    public static javax.swing.JTextField txtidsociomodal;
    // End of variables declaration//GEN-END:variables

    public void setRowData(Membresia bean) throws ParseException {

        PlanesController planes = new PlanesController();
        PromocionesController promos = new PromocionesController();
        //Obteniendo el objeto a comparar con el combo planes
        Planes plan;
        plan = planes.leerxid(bean.getIdPlan());

        //Obteniendo el objeto a comparar con el combo promociones
        Promociones promo;
        promo = promos.leerxid(bean.getIdPromociones());

//         CargaComponentes carga= new CargaComponentes();
//         carga.cargaIdEmpleado(jlblnomemp);
//        this.setTitle("ModificaSocio");
        jLabel1.setText("Modificar Membresia");
        jtxtidmem.setVisible(true);
        btnModificar.setVisible(true);
        btnRegistrar.setVisible(false);
        btnLimpiar.setVisible(false);
        cboestado.addItem("Congelado");
        
        jtxtidmem.setText(bean.getIdMembresia());

        txtidsociomodal.setText(bean.getIdSocio());
        txtidsociomodal.setEditable(false);

        jComboBoxPlanes1.getModel().setSelectedItem(plan);
        jComboBoxPlanes1.setEnabled(false);
        jComboBoxPromociones1.getModel().setSelectedItem(promo);
        jComboBoxPromociones1.setEnabled(false);

        datefini.setSelectedDate(IngresarFecha(bean.getF_Inicio()));
        datefini.setEnabled(false);
        dateffin.setSelectedDate(IngresarFecha(bean.getF_Fin()));

        if ("Culminado".equals(bean.getEstado())) {
            dateffin.setEnabled(false);
            cboestado.setEnabled(false);
            btnModificar.setEnabled(false);

        }

        cboestado.setSelectedItem(bean.getEstado());

    }

}
